# Generated by Django 2.1 on 2018-08-06 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediaplatform', '0007_update_arrayfield_defaults'),
        ('mediaplatform_jwp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('key', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('updated', models.BigIntegerField(editable=False, help_text='Last updated timestamp')),
                ('channel', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jwp', to='mediaplatform.Channel')),
            ],
        ),
    ]
