# Generated by Django 2.1 on 2018-08-28 15:59

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaplatform_jwp', '0002_add_channel_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedResource',
            fields=[
                ('key', models.CharField(help_text='A unique textual key for this resource. E.g. for videos, this can be the JWPlatform video key', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(help_text='The resource data itself')),
                ('type', models.CharField(choices=[('video', 'Video'), ('channel', 'Channel')], help_text='The JWPlatform resource type cached in this model', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time at which this cached resource was first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time at which this cached resource was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='The date and time at which this cached resource was deleted', null=True)),
            ],
            options={
                'db_table': 'mediaplatform_jwp_cachedresource',
            },
            bases=(models.Model,),
        ),
        migrations.AddIndex(
            model_name='cachedresource',
            index=django.contrib.postgres.indexes.GinIndex(fields=['data'], name='mediaplatfo_data_55af3a_gin'),
        ),
        migrations.AddIndex(
            model_name='cachedresource',
            index=models.Index(fields=['type'], name='mediaplatfo_type_f50245_idx'),
        ),
    ]
