# Generated by Django 2.1 on 2018-09-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaplatform_jwp', '0003_auto_20180828_1559'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cachedresource',
            table=None,
        ),
    ]
