# Generated by Django 2.1 on 2018-08-03 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediaplatform', '0006_link_media_items_to_channel'),
        ('legacysms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='collection',
        ),
        migrations.AddField(
            model_name='collection',
            name='channel',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms', to='mediaplatform.Channel'),
        ),
    ]
