# Generated by Django 2.1 on 2018-08-09 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediaplatform', '0010_alter_playlist_media_items_field'),
        ('legacysms', '0002_link_collections_to_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='playlist',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms', to='mediaplatform.Playlist'),
        ),
    ]
