# docker-compose file for local development and testing with container image.
#
# Extends compose/base.yml so launch services via:
#
#   docker-compose -f compose/base.yml -f compose/production.yml
version: '3.2'
services:
  # Main web application service
  production_app:
    build:
      context: ..
      dockerfile: ./Dockerfile
    expose:
      - "8080"
    ports:
      - "8000:8080"
    depends_on:
      - "db"
      - "hydra"
      - "lookupproxy"
      - "hydra-create-clients"
    env_file:
      - base.env
      - ../secrets.env
