# Generated by Django 2.1.3 on 2018-11-22 15:44

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import oaipmh.models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaplatform', '0026_add_initially_fetched_from_url_to_media_item'),
        ('oaipmh', '0002_create_matterhorn_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, help_text='Identifier for series. Blank for records with no series set', max_length=1024)),
                ('title', models.TextField(blank=True, help_text='Human-readable title', max_length=1024)),
                ('view_crsids', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=oaipmh.models._blank_array, help_text='Initial list of crsids of users allowed to view items in series', size=None)),
                ('view_lookup_groups', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=oaipmh.models._blank_array, help_text='Initial list of Lookup group numeric ids allowed to view items in series', size=None)),
                ('view_lookup_insts', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=oaipmh.models._blank_array, help_text='Initial list of Lookup institutions allowed to view items in series', size=None)),
                ('view_is_public', models.BooleanField(default=False, help_text='Initial flag indicating if media items are public')),
                ('view_is_signed_in', models.BooleanField(default=False, help_text='Initial flag indicating if media items are visible to all signed in users')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('playlist', models.ForeignKey(blank=True, help_text='Playlist associated with this series', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediaplatform.Playlist')),
                ('repository', models.ForeignKey(help_text='Repository this series was fetched from', on_delete=django.db.models.deletion.CASCADE, to='oaipmh.Repository')),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.AddField(
            model_name='matterhornrecord',
            name='series',
            field=models.ForeignKey(blank=True, help_text='Associated series', null=True, on_delete=django.db.models.deletion.SET_NULL, to='oaipmh.Series'),
        ),
        migrations.AlterUniqueTogether(
            name='series',
            unique_together={('repository', 'identifier')},
        ),
    ]
