# Generated by Django 2.1.3 on 2018-11-22 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediaplatform', '0025_create_channel_permissions'),
        ('oaipmh', '0003_create_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Identifier for track', max_length=1024)),
                ('url', models.URLField(help_text='URL of track', max_length=1024)),
                ('xml', models.TextField(help_text='Original XML representation of track')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('matterhorn_record', models.ForeignKey(help_text='Matterhorn record containing this track', on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='oaipmh.MatterhornRecord')),
                ('media_item', models.ForeignKey(blank=True, help_text='Media item for this track', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oaipmh_track', to='mediaplatform.MediaItem')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('matterhorn_record', 'identifier')},
        ),
    ]
