# Generated by Django 2.1.3 on 2018-11-27 14:23

import django.contrib.postgres.fields
from django.db import migrations, models
import oaipmh.models


class Migration(migrations.Migration):

    dependencies = [
        ('oaipmh', '0004_create_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='track_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=oaipmh.models._default_track_types, help_text='List of track types which will be converted to media items for this series. If changed, a full cleanup will need to be re-run', size=None),
        ),
    ]
