# Generated by Django 2.0.6 on 2018-06-22 13:51

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedResource',
            fields=[
                ('key', models.CharField(help_text='A unique textual key for this resource. E.g. for videos, this can be the JWPlatform video key', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(help_text='The resource data itself')),
                ('type', models.CharField(choices=[('video', 'Video')], help_text='The JWPlatform resource type cached in this model', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time at which this cached resource was first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time at which this cached resource was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='The date and time at which this cached resource was deleted', null=True)),
            ],
            managers=[
                ('videos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='cachedresource',
            index=django.contrib.postgres.indexes.GinIndex(fields=['data'], name='smsjwplatfo_data_924ace_gin'),
        ),
        migrations.AddIndex(
            model_name='cachedresource',
            index=models.Index(fields=['type'], name='smsjwplatfo_type_6ddb5d_idx'),
        ),
    ]
