# Generated by Django 2.1 on 2018-08-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsjwplatform', '0001_create_cached_resource'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cachedresource',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='cachedresource',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('channel', 'Channel')], help_text='The JWPlatform resource type cached in this model', max_length=20),
        ),
    ]
