# Generated by Django 2.1 on 2018-08-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsjwplatform', '0002_add_channels_to_cachedresource'),
    ]

    database_operations = [
        migrations.AlterModelTable('CachedResource', 'mediaplatform_jwp_cachedresource')
    ]

    state_operations = [
        migrations.DeleteModel('CachedResource')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
