# Generated by Django 2.0.7 on 2018-07-11 16:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediaplatform', '0002_update_primary_key_max_len'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description for collection'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='edit_permission',
            field=models.OneToOneField(default=None, help_text='Restriction on who can modify this collection', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mediaplatform.Permission'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='media_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=[], help_text='Primary keys of media items in this collection', size=None),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.TextField(blank=True, default='', help_text='Title of collection'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='view_permission',
            field=models.OneToOneField(default=None, help_text='Restriction on who can see which items are in this collection', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mediaplatform.Permission'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='copyright',
            field=models.TextField(blank=True, default='', help_text='Free text describing Copyright holder'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description of media item'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='downloadable',
            field=models.BooleanField(default=False, help_text='If this item can be viewed, can it also be downloaded?'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='edit_permission',
            field=models.OneToOneField(default=None, help_text='Restriction on who can modify this item', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mediaplatform.Permission'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='language',
            field=models.CharField(default=None, help_text='ISO 639-3 three letter language code describing majority language used in this item', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='title',
            field=models.TextField(blank=True, default='', help_text='Title of media item'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='view_permission',
            field=models.OneToOneField(default=None, help_text='Restriction on who can see/hear this item', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mediaplatform.Permission'),
        ),
    ]
