# Generated by Django 2.0.7 on 2018-07-30 13:55

from django.db import migrations, models
import django.db.models.deletion
import mediaplatform.models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaplatform', '0003_tweak_media_item_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadEndpoint',
            fields=[
                ('id', models.CharField(default=mediaplatform.models._make_token, editable=False, max_length=11, primary_key=True, serialize=False)),
                ('url', models.URLField(editable=False, help_text='URL to POST file data to')),
                ('expires_at', models.DateTimeField(editable=False, help_text='Expiry time of URL')),
                ('item', models.OneToOneField(editable=False, help_text='item this upload URL is for', on_delete=django.db.models.deletion.CASCADE, related_name='upload_endpoint', to='mediaplatform.MediaItem')),
            ],
        ),
    ]
