# Generated by Django 2.0.7 on 2018-07-31 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediaplatform', '0005_add_channel_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='channel',
            field=models.ForeignKey(null=True, help_text='Channel containing media item', on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='mediaplatform.Channel'),
        ),
    ]
