# Generated by Django 2.1 on 2018-08-02 09:11

import django.contrib.postgres.fields
from django.db import migrations, models
import mediaplatform.models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaplatform', '0006_link_media_items_to_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='media_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=mediaplatform.models._blank_array, help_text='Primary keys of media items in this collection', size=None),
        ),
        migrations.AlterField(
            model_name='collection',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=mediaplatform.models._blank_array, help_text='Tags/keywords for item', size=None),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=mediaplatform.models._blank_array, help_text='Tags/keywords for item', size=None),
        ),
        migrations.AlterField(
            model_name='permission',
            name='crsids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=mediaplatform.models._blank_array, size=None),
        ),
        migrations.AlterField(
            model_name='permission',
            name='lookup_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=mediaplatform.models._blank_array, size=None),
        ),
        migrations.AlterField(
            model_name='permission',
            name='lookup_insts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=mediaplatform.models._blank_array, size=None),
        ),
    ]
