# Generated by Django 2.1 on 2018-08-06 14:36

from django.db import migrations, models
import django.db.models.deletion
import mediaplatform.models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaplatform', '0007_update_arrayfield_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.CharField(default=mediaplatform.models._make_token, editable=False, max_length=11, primary_key=True, serialize=False)),
                ('title', models.TextField(help_text='Title of the playlist')),
                ('description', models.TextField(blank=True, default='', help_text='Description of the playlist')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(help_text='channel containing playlist', on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='mediaplatform.Channel')),
            ],
        ),
        migrations.AddField(
            model_name='permission',
            name='allows_view_playlist',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_permission', to='mediaplatform.Playlist'),
        ),
    ]
