# Generated by Django 2.1 on 2018-08-07 08:39

import django.contrib.postgres.fields
from django.db import migrations, models
import mediaplatform.models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaplatform', '0008_add_playlist_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='media_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=11), default=mediaplatform.models._blank_array, help_text='Primary keys of media items in this playlist', size=None),
        ),
    ]
