# Generated by Django 2.1 on 2018-08-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaplatform', '0010_add_owner_inst_to_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='allows_edit_item',
        ),
    ]
