# Generated by Django 2.1 on 2018-08-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaplatform', '0011_delete_collection_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='owning_lookup_inst',
            field=models.CharField(default='', help_text='Lookup instid for institution which "owns" this channel', max_length=255),
        ),
    ]
