# Generated by Django 2.1.1 on 2018-09-10 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mediaplatform', '0014_auto_20180905_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date from which video is visible'),
        ),
    ]
