# Generated by Django 2.1.1 on 2018-09-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaplatform', '0015_auto_20180910_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaitem',
            options={'permissions': (('download_mediaitem', 'Can download media associated with a media item'),)},
        ),
    ]
