# Generated by Django 2.1.2 on 2018-10-19 14:32

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaplatform', '0019_auto_20181015_1544'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mediaitem',
            name='mediaplatfo_text_se_d418e1_gin',
        ),
        migrations.AddIndex(
            model_name='mediaitem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text_search_vector'], name='mediaplatfo_text_se_61f492_gin'),
        ),
    ]
