# Generated by Django 2.1.2 on 2018-10-19 14:47

from django.db import migrations, models
import mediaplatform.models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaplatform', '0020_update_gin_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.CharField(default=mediaplatform.models._make_token, editable=False, max_length=11, primary_key=True, serialize=False)),
                ('description', models.TextField(help_text='Human readable description')),
                ('lookup_instid', models.CharField(help_text='Lookup instid for institution which operates this billing account.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='billingaccount',
            index=models.Index(fields=['created_at'], name='mediaplatfo_created_eb268f_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaccount',
            index=models.Index(fields=['updated_at'], name='mediaplatfo_updated_4c669a_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaccount',
            index=models.Index(fields=['lookup_instid'], name='mediaplatfo_lookup__0d77f4_idx'),
        ),
    ]
