# Generated by Django 2.1.2 on 2018-10-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaplatform', '0022_move_channel_institution_to_billing_account'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['created_at'], name='mediaplatfo_created_9c6424_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['deleted_at'], name='mediaplatfo_deleted_043765_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaitem',
            index=models.Index(fields=['created_at'], name='mediaplatfo_created_fbeb5b_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaitem',
            index=models.Index(fields=['deleted_at'], name='mediaplatfo_deleted_98a707_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['created_at'], name='mediaplatfo_created_de3ebd_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['deleted_at'], name='mediaplatfo_deleted_7cde4f_idx'),
        ),
    ]
