# Generated by Django 2.1.2 on 2018-10-29 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediaplatform', '0023_add_remaining_at_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='allows_create_channel_on_billing_account',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_create_permission', to='mediaplatform.BillingAccount'),
        ),
    ]
