# Generated by Django 2.1.2 on 2018-10-29 15:29

from django.db import migrations, models
import django.db.models.deletion


def create_billing_account_permissions(apps, schema_editor):
    """
    Create an empty permission for each billing account which lacks one.

    """
    BillingAccount = apps.get_model('mediaplatform', 'BillingAccount')
    Permission = apps.get_model('mediaplatform', 'Permission')
    for account in BillingAccount.objects.all():
        # Note: we cannot simply filter the call to BillingAccount.objects above because the
        # associated index is not yet fully set up.
        if not hasattr(account, 'channel_create_permission'):
            Permission.objects.create(allows_create_channel_on_billing_account=account)


def no_op(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mediaplatform', '0024_add_channel_create_permission'),
    ]

    operations = [
        # The reverse operation is a no-op because we shouldn't needlessly delete data.
        migrations.RunPython(create_billing_account_permissions, no_op)
    ]

