# Generated by Django 2.1.3 on 2018-11-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaplatform', '0025_create_channel_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='initially_fetched_from_url',
            field=models.URLField(blank=True, default='', help_text='If set at creation time, video will be fetched from this URL', max_length=2048),
        ),
    ]
